### ISSUE TITLE
voting urls

### ISSUE THREAD

**Issue by wizzywig444** [Ben12345rocks/VotingPlugin#1247]
Version:
1.18.2

Describe:
i keep getting a error with my votesite.yml settings
WARN [VotingPlugin] Detected an issue with voting sites, check the server startup log for more details: https://github.com/BenCodez/VotingPlugin/wiki/Votifier-Troubleshooting
 
Configs:
https://pastebin.com/QcYJjTsq

Additional context:
please help i have been trying to sort this out for days

**Comment by BenCodez** [comment]
https://github.com/BenCodez/VotingPlugin/wiki/Votifier-Troubleshooting
Check this.

**Comment by wizzywig444** [comment]
I already have but I don't understand why it's not working I have tried
everything

**Comment by BenCodez** [comment]
Do you get the message in console as stated on the wiki page?

**Comment by wizzywig444** [comment]
Yes and the test worked and gave the rewards but the others don't give
rewards it says they voted but didn't give them rewards

**Comment by BenCodez** [comment]
Does the message pop up on the actual voting site? Did you set the correct service site?

**Comment by wizzywig444** [comment]
I'm not sure I have tried to change it so many times can you please have a
look at my pastebin and see where I have gone wrong as I really can't
figure it out

**Comment by BenCodez** [comment]
Double check the votes reach the server first.

**Comment by wizzywig444** [comment]
It says in game thanks you have voted but it don't give the rewards and it
also shows up on the voting sites that there is a vote and it was
successful

**Comment by BenCodez** [comment]
Did it generate a votesite?
Try the commands like this?
https://github.com/BenCodez/VotingPlugin/wiki/Rewards

**Comment by ghost** [comment]
If the message appears, but the reward ist not given, it implies the vote reaches your server and gets registered, but the reward command is not properly executed. Try using the direct plugin command like you would if you had to setup an alias in commands.yml.

For example with CMI if you wanted to give money, instead of using:
```
    Rewards:
      Commands:
      - money add %player% 1500
```

use the command this way:
```
    Rewards:
      Commands:
      - cmi:cmi money add %player% 1500
```


Also double check you're using the command correctly by testing it ingame first and check if `Console:` is needed at all after `Commands:` in your Rewards section.

**Comment by wizzywig444** [comment]
Yes I did but under the commands I done a space in then done Console: then
under on the same line I done - 'crates key give %player% vote 1'
